sources:
  - name: uniswap-v4-base-3
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/${VITE_THE_GRAPH_API_KEY}/subgraphs/id/Gqm2b5J85n1bhCyDMpGbtbVn4935EvvdyHdHrx3dibyj

  - name: aerodrome-base-full
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/${VITE_THE_GRAPH_API_KEY}/subgraphs/id/GENunSHWLBXm59mBSgPzQ8metBEp9YDfdqwFr91Av1UM

documents:
  - ./lib/graphql/query.graphql
